name: Deploy HelloWorld App

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      run_id:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (develop / qa / main)'
        required: true
        type: string


permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  resolve-run-id:
    name:  Artifact ID
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.get-run.outputs.run_id }}
      branch: ${{ steps.get-branch.outputs.branch }}
    steps:
      - name: Set branch value
        id: get-branch
        run: echo "branch=${{ inputs.branch }}" >> "$GITHUB_OUTPUT"

      - name: Get run_id (from input or latest successful build)
        id: get-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ inputs.run_id }}" ]; then
            echo "run_id=${{ inputs.run_id }}" >> "$GITHUB_OUTPUT"
          else
            LATEST_RUN_ID=$(gh run list \
              --repo ${{ github.repository }} \
              --workflow "Build HelloWorld App" \
              --branch "${{ inputs.branch }}" \
              --status success \
              --limit 1 \
              --json databaseId \
              --jq '.[0].databaseId')
            echo "run_id=$LATEST_RUN_ID" >> "$GITHUB_OUTPUT"
          fi

  deploy-dev:
    name: Deploy to development environment
    needs: resolve-run-id
    if: ${{ needs.resolve-run-id.outputs.branch == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: helloworld-artifact
          path: ./publish
          repository: ${{ github.repository }}
          run-id: ${{ needs.resolve-run-id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App (DEV)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.DEV_FUNCTION_APP_NAME }}
          package: ./publish/helloworld-artifact.zip
      - name: Logout from Azure
        if: always()
        run: az logout || true

  deploy-qa:
    name: Deploy to QA environment
    needs: resolve-run-id
    if: ${{ needs.resolve-run-id.outputs.branch == 'qa' }}
    runs-on: ubuntu-latest
    environment: qa
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: helloworld-artifact
          path: ./publish
          repository: ${{ github.repository }}
          run-id: ${{ needs.resolve-run-id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.QA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QA_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App (QA)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.QA_FUNCTION_APP_NAME }}
          package: ./publish/helloworld-artifact.zip
      - name: Logout from Azure
        if: always()
        run: az logout

  deploy-prod:
    name: Deploy to prod environment
    needs: resolve-run-id
    if: ${{ needs.resolve-run-id.outputs.branch == 'main' }}
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: helloworld-artifact
          path: ./publish
          repository: ${{ github.repository }}
          run-id: ${{ needs.resolve-run-id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.Prod_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.Prod_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.Prod_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App (Prod)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.PROD_FUNCTION_APP_NAME }}
          package: ./publish/helloworld-artifact.zip
      - name: Logout from Azure
        if: always()
        run: az logout
