name: .NET Console App CI

on:
  push:
    branches:
      - main
      - development
      - qa

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/HelloWorld/HelloWorld.csproj

      - name: Build project
        run: dotnet build ./src/HelloWorld/HelloWorld.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./src/HelloWorld/HelloWorld.csproj --configuration Release --output ./publish --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld
          path: ./publish
